apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc
spec:
  storageClassName: "gitlab"
  volumeName: gitlab-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
