apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv
  labels:
    type: local
spec:
  storageClassName: "gitlab"
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/dfs/k8s/data"
